### ISSUE TITLE
1.5.7 Corrupted Troops

### ISSUE THREAD

**Issue by Manpapper** [Splintertx/DynaCulture#6]
Hi Splintertx
Another crash.
When there is only corrupted troops in a settlement the game seems to crash because there is no more found to calculate since trooper rooster is empty. The food calculation is probably just after the hourlyPartyTick of DynaCulture (since the game detected some troop)
![image](https://user-images.githubusercontent.com/59976577/109543732-f48e1e80-7ac6-11eb-90c4-138216edbfcf.png)
I think here the fix would the to add a random troop to the troop rooter, but personnally I don't know how to do it
Save file and dynaculture.dat below
https://1fichier.com/?89yaki90oswu4dmd33i2

**Comment by Manpapper** [comment]
`at TaleWorlds.CampaignSystem.SandBox.GameComponents.Map.DefaultMobilePartyFoodConsumptionModel.CalculateDailyFoodConsumptionf(MobileParty party, Boolean includeDescription)
at TaleWorlds.CampaignSystem.MobileParty.get_FoodChange()
at TaleWorlds.CampaignSystem.SandBox.CampaignBehaviors.AiBehaviors.AiVisitSettlementBehavior.AiHourlyTick(MobileParty mobileParty, PartyThinkParams p)
at TaleWorlds.CampaignSystem.MbEvent`2.InvokeList(EventHandlerRec`2 list, T1 t1, T2 t2)
at TaleWorlds.CampaignSystem.CampaignEvents.AiHourlyTick(MobileParty party, PartyThinkParams partyThinkParams)
at TaleWorlds.CampaignSystem.CampaignEventDispatcher.AiHourlyTick(MobileParty party, PartyThinkParams partyThinkParams)
at TaleWorlds.CampaignSystem.SandBox.CampaignBehaviors.AiBehaviors.AiPartyThinkBehavior.PartyHourlyAiTick(MobileParty mobileParty)
at TaleWorlds.CampaignSystem.SandBox.CampaignBehaviors.AiBehaviors.AiPartyThinkBehavior.TickPartialHourlyAi()
at TaleWorlds.CampaignSystem.MbEvent.InvokeList(EventHandlerRec list)
at TaleWorlds.CampaignSystem.CampaignEvents.TickPartialHourlyAi()
at TaleWorlds.CampaignSystem.CampaignEventDispatcher.TickPartialHourlyAi()
at TaleWorlds.CampaignSystem.Campaign.Tick(Single dt)
at TaleWorlds.CampaignSystem.Campaign.RealTick(Single realDt)
at TaleWorlds.CampaignSystem.MapState.OnMapModeTick(Single dt)
at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
at TaleWorlds.Core.Game.OnTick(Single dt)
at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
at TaleWorlds.MountAndBlade.Module.OnApplicationTick(Single dt)
at TaleWorlds.DotNet.Managed.ApplicationTick(Single dt)`

**Comment by Manpapper** [comment]
Also something weird happen
I add some log each time a settlement changed culture (the log is without loading save):
3/1/2021 8:02:08 PM: 132021 : The culture Druimmor changed from Battania to Vlandia 
3/1/2021 8:02:12 PM: 132021 : The culture Tor Melina changed from Battania to Vlandia 
3/1/2021 8:05:41 PM: 132021 : The culture Usanc changed from Vlandia to Aserai 
3/1/2021 8:06:31 PM: 132021 : The culture Druimmor Castle changed from Battania to Vlandia 
3/1/2021 8:06:50 PM: 132021 : The culture Gamardan changed from Empire to Aserai 
3/1/2021 8:07:38 PM: 132021 : The culture Usanc Castle changed from Vlandia to Aserai 
3/1/2021 8:10:09 PM: 132021 : The culture Thractorae Castle changed from Empire to Aserai 

You can see for exemple that Usanc changed 2 time to Aserai from vlandia without passing from vlandia to aserai which is weird any idea?
Same for Druimmor

**Comment by Manpapper** [comment]
@Splintertx

**Comment by Splintertx** [comment]
I just pushed a fix that resolves the issue for the provided save. It appears that your campaign is riddled with our friend "TroopRosterElement". Can you have a look before I make a new release?

**Comment by Manpapper** [comment]
What's is weird is that i don't have any corrupted troop until I load a game.
I still have a crash after moving a little on the map after loading.
I also checked the game code wondering where the problem come from.
The game seems to use the culture to provide recruits:
`private void UpdateVolunteersOfNotables(bool initialRunning = false)
{
	foreach (Settlement settlement in Campaign.Current.Settlements)
	{
		if ((settlement.IsTown && !settlement.Town.InRebelliousState) || (settlement.IsVillage && !settlement.Village.Bound.Town.InRebelliousState))
		{
			foreach (Hero hero in settlement.Notables)
			{
				if (hero.CanHaveRecruits)
				{
					bool flag = false;
					CultureObject cultureObject = (hero.CurrentSettlement != null) ? hero.CurrentSettlement.Culture : hero.Clan.Culture;
					CharacterObject basicTroop = cultureObject.BasicTroop;
					double num = (hero.IsRuralNotable && hero.Power >= 200f) ? 1.5 : 0.5;
					float num2 = 200f;
...`
I will try to look into this after work.

**Comment by Splintertx** [comment]
Each culture stores a variety of troop types that are referenced by a generic name, like "melee_militia_troop", "elite_basic_troop" etc. These are defined in SandBox Core/Module Data/spcultures.xml and refer to entries in spnpccharacters.xml.

**Comment by Manpapper** [comment]
I still don't understand why the game spawn null troops.

**Comment by Manpapper** [comment]
Your fix didn't fix a new dave I had.
The game was crashing on the first load, deplacing the remove all troops and Recruits in OnGameLoaded seems to solve a part of the problem.
I also had to add this chuck of code in RemoveCorrupted troops:
`                try
                {
                    float foodchange = mobileParty.FoodChange;
                }
                catch (Exception ex)
                {
                    InformationManager.DisplayMessage(new InformationMessage(new TextObject($"(DynaCulture) The Party {mobileParty.Name} have been delete due to corrupted troops.", (Dictionary<string, object>)null).ToString(), Colors.Yellow));
                    mobileParty.RemoveParty();
                }`
I don't know if there is a simple way in do this.
The problem occurs when even by removing each corrupted troop the party is still coorupted (maybe there is something else which cause it didn't find it thought)
The save file and dynaculture which cause this crash:
https://1fichier.com/?cfsja5igjd4z2fi8e629
i still have other crash i'm looking into it

**Comment by Manpapper** [comment]
Is there a way to access this type of function?
![image](https://user-images.githubusercontent.com/59976577/109994528-b0d92600-7d0d-11eb-9979-615833444b54.png)

**Comment by Manpapper** [comment]
Nevermind I found it
Thanks to this i found that there was corrupted troop in the prison roster too
![image](https://user-images.githubusercontent.com/59976577/109996539-9bfd9200-7d0f-11eb-8aae-20129ac79f21.png)

**Comment by Splintertx** [comment]
Pushed an update for this. Also moved the campaign load cleanup code so parties will be cleaned before any game ticks occur.

**Comment by Manpapper** [comment]
I found something interesting.
When changing town culture notable culture become a culture object with everything at null
![image](https://user-images.githubusercontent.com/59976577/110005213-86d93100-7d18-11eb-9246-5fbdbda648ba.png)

![image](https://user-images.githubusercontent.com/59976577/110005146-74f78e00-7d18-11eb-8a6a-7f467b3de93a.png)

**Comment by Manpapper** [comment]
How does villages handle recruit since there isn't any notable?

**Comment by Splintertx** [comment]
Villages work the same way as towns, there are still notables with up to 6 recruits each.

**Comment by Manpapper** [comment]
My bad town and village are settlements so no problem here.
Maybe it will fix the whole thing

**Comment by Splintertx** [comment]
I am not seeing the notables' culture changing when changing the settlement. I do not think there is a reason to do so, as the recruits are spawned based on the settlement culture rather than the individual.

**Comment by Manpapper** [comment]
How is the volunteertype Updated?

**Comment by Splintertx** [comment]
As far as I can tell, RecruitmentCampaignBehavior.UpdateVolunteersOfNotables is the only time VolunteerTypes is added to. This doesn't include other mods, like your Improved Garrisons. I've left your save going on pure Native + DynaCulture for ingame weeks now with no issues. Have you tried disabling Improved Garrisons to see if you still get corrupted troops?

**Comment by Manpapper** [comment]
No problem so far even with Improved Garrisons.

**Comment by Manpapper** [comment]
maybe like 1 week or so
